feat: lint-file subcommand
fsfe/reuse-tool pull request #1055
Opened 2024-08-01 20:45 UTC by klmcadams

Added `lint-file` subcommand to allow people to lint specified file(s). In the command line, you can run `reuse lint-file <files>`. For example, `reuse lint-file src/reuse/download.py src/reuse/_annotate.py`. If you only run `reuse lint-file` with no files listed, then it will lint all files (as if you were just running `reuse lint`).

When running pre-commit, I get this message:

```
pylint...................................................................Failed
- hook id: pylint
- exit code: 8

************* Module reuse.report
src\reuse\report.py:280:4: R0914: Too many local variables (17/15) (too-many-locals)
```

If this is an issue, I can try to adjust the function to use fewer local variables. 

Let @SMoraisAnsys or I know if you have any questions or concerns! This PR addresses the suggestions in #903.

Here is a picture of running reuse lint-files in the command line with a file that doesn't exist (dne_file.py), two files that exist and are compliant, and one file that exists but is not compliant (empty_file.py):

![lint_files_example](https://github.com/user-attachments/assets/8bb36087-b010-443a-864a-3c970e05ddf5)

- [x] Added a change log entry in `changelog.d/<directory>/`.
- [x] Added self to copyright blurb of touched files.
- [x] Added self to `AUTHORS.rst`.
- [x] Wrote tests.
- [x] Documented my changes in `docs/man/` or elsewhere.
- [x] My changes do not contradict
      [the current specification](https://reuse.software/spec/).
- [x] I agree to license my contribution under the licenses indicated in the
      changed files.

2024-08-04 04:59 UTC, carmenbianca commented
Hi @klmcadams ! Thank you so much for this PR. Unfortunately I do not have time to review it this or next week.

2024-08-05 12:07 UTC, klmcadams commented
@carmenbianca that's okay! Thanks for letting me know

2024-09-05 14:04 UTC, carmenbianca requested changes
I did a cursory review. There's a number of things that need to change. Because I have time and this feature has some priority for me, I will work on patching this PR up.

Thank you @klmcadams !

2024-09-05 14:04 UTC, carmenbianca commented on tests/test_lint.py
> +    assert "# UNUSED LICENSES" in result
This is incorrect. The purpose of `lint-file` is not to do the exact same thing as `lint`, but on a subset of the project. The purpose of `lint-file` is to do a subset of what `lint` does on a subset of the project. Or, crudely put, `lint-file` should check whether each file has a copyright holder and a licence. In addition, it wouldn't hurt to also check for missing licences. The rest is covered by `lint`.

The idea is that this makes for a quicker pre-commit hook that doesn't check absolutely everything in a project.

2024-09-05 17:02 UTC, klmcadams commented on .pre-commit-hooks.yaml
> +  args: ["lint", "lint-file"]
I was able to call `reuse lint-file` while testing it locally, so I don't think you would have to call `reuse lint lint-file`. I'm not 100% sure though

2024-09-05 17:10 UTC, klmcadams commented
@carmenbianca Thanks for the review! Let me know if I can help in any way

2024-09-06 14:41 UTC, carmenbianca commented on src/reuse/report.py
> +    def get_lint_results(
I ended up turning this into a separate function used by two classes.

2024-09-06 14:46 UTC, carmenbianca commented on .pre-commit-hooks.yaml
> +  args: ["lint", "lint-file"]
This is the pre-commit hook, so it won't be used at all when you type `reuse lint-file` :) Instead, when someone has a pre-commit config which uses our hook, _they_ will end up running `reuse lint lint-file` on their machine.

If you want to fix this, you can. You basically just need to copy the top-level list item in this file, paste it, and adjust it to use `lint-file` and to accept file args. You can then test it using a separate project with this pre-commit config:

```yaml
repos:
  - repo: https://github.com/klmcadams/reuse-tool
    rev: feat/lint-file
    hooks:
      - id: NAME_OF_HOOK
```

(replace `NAME_OF_HOOK`)

2024-09-06 14:46 UTC, carmenbianca commented on tests/test_lint.py
> +    assert "# UNUSED LICENSES" in result
Implemented this!

2024-09-06 14:50 UTC, carmenbianca commented
Rebased on top of main to fix a problem I had (#1067) while testing, and patched this up in one rather big commit.

Because the behaviour of `lint-file` is very slightly esoteric (as are so many things in `reuse`…), I will need to set aside some additional time to improve the man page.

Thanks a lot for the template to work on top of @klmcadams ! You had a lot of the right ideas.

If you have time, I would love a code review on this. If not, that is very understandable :) It's taken me a month to respond to you, after all.

2024-09-09 07:46 UTC, SMoraisAnsys approved these changes
LGTM. You just need to remove the "Unused licenses" section from `reuse-lint-file.rst`.

2024-09-09 07:46 UTC, SMoraisAnsys commented on docs/man/reuse-lint-file.rst
> +
```suggestion
```

2024-09-10 10:34 UTC, carmenbianca approved these changes

2024-09-10 10:34 UTC, carmenbianca commented
Perfect, merging! I'll get a release of this out the door some time soon. Thank you @klmcadams and @SMoraisAnsys !

2024-09-10 10:34 UTC, merged