Implement caching for license texts
fsfe/reuse-tool pull request #503
Opened 2022-02-19 14:09 UTC by alois31

License texts are not expected to ever change. Cache them so that
network access is only required when first dowloading a new license.

Signed-off-by: Alois Wohlschlager <alois1@gmx-topmail.de>

2022-02-22 16:16 UTC, siiptuo requested changes
The license text are mostly static but there has been some changes to formatting over the years. However, caching the licenses is a good idea and here's some suggestion mostly on code style.

2022-02-22 16:16 UTC, siiptuo commented on src/reuse/download.py
> +        os.makedirs(cachedir, exist_ok=True)
```suggestion
        cachedir.mkdir(parents=True, exist_ok=True)
```

2022-02-23 11:22 UTC, mxmehl commented on src/reuse/download.py
> +    cachehome = os.environ["XDG_CACHE_HOME"] if "XDG_CACHE_HOME" in os.environ else Path(os.environ["HOME"]) / ".cache"
Would that also work on Windows and MacOS machines? We have a few users on other operating systems.

2022-02-23 11:25 UTC, mxmehl commented
As @siiptuo mentioned, license texts in SPDX tend to change here and there, often fixing bugs that users benefit from. I would be fine with some time-limited caching, e.g. a few days or bound to the REUSE tool version, so that with a new version the cached license texts are refreshed.

However, we should cover other operating systems. Is `XDG_CACHE_HOME` understood on MacOS and Windows as well?

2022-02-23 11:50 UTC, siiptuo commented on src/reuse/download.py
> +    cachehome = os.environ["XDG_CACHE_HOME"] if "XDG_CACHE_HOME" in os.environ else Path(os.environ["HOME"]) / ".cache"
I think that with `Path.home` it should work on all platforms but this should be tested. More ideal solution would be to use a library like [appdirs](https://pypi.org/project/appdirs/).

2022-02-24 10:22 UTC, carmenbianca commented
> However, we should cover other operating systems. Is `XDG_CACHE_HOME` understood on MacOS and Windows as well?

[appdirs](https://pypi.org/project/appdirs/) covers this use case. It's a fairly common dependency, but I'm not sure we should add it.

2022-02-24 12:53 UTC, mxmehl commented on src/reuse/download.py
> +    cachehome = os.environ["XDG_CACHE_HOME"] if "XDG_CACHE_HOME" in os.environ else Path(os.environ["HOME"]) / ".cache"
The CI has a number of other issues currently, caused by an update of an unpinned dependency of Jinja, markupsafe. Was it this error?

We are usually very cautious of adding new dependencies. However, if it's really necessary, their should at least be packaged in Debian and Fedora.

2022-02-25 14:04 UTC, alois31 commented on src/reuse/download.py
> +    cachehome = os.environ["XDG_CACHE_HOME"] if "XDG_CACHE_HOME" in os.environ else Path(os.environ["HOME"]) / ".cache"
It was actually about appdirs itself. It is packaged (at least) on all of Debian, Fedora and openSUSE.

2022-02-26 14:24 UTC, seabass-labrax commented
How about a cache based on the current SPDX License List version, rather than a duration? This could be done by scraping the version label on https://spdx.org/licenses, fetching the latest tag from the SPDX License List Git repository (although that wouldn't work if the Git command isn't present) or by making a GitHub API request to find the latest release.

2022-05-06 05:22 UTC, floriansnow commented
So how should we proceed with this?  I think it's nice to heave, but probably not a deal breaker for most use cases.  There are still a few open questions here and by now also merge conflicts.  Should we invest the time or table this for now because it's probably "just" nice to have?

2022-05-06 08:44 UTC, mxmehl commented
I would also consider it nice-to-have, but as we learnt in this thread, some questions/issues would have to be resolved first:

- Logic to detect the cache dir. `appdirs` works but saw its last release in 2020. Is there a successor that's also widely available in distros?
- Limited caching period, based on SPDX License List version (or alternatively REUSE tool version). Both are not perfect indicators, but at least the former should be quite sufficient.

2022-05-13 16:46 UTC, linozen commented
IMHO, the complexity involved in implementing this properly (making sure licenses are up-to-date etc.) while adding only well-maintained and broadly supported dependencies stands in no relationship to the benefit this could generate for users. If the only use-case here remains the one outlined by @alois31, I am in favor of closing this.

2022-08-31 14:30 UTC, closed without merging