Extend changelog for 2.0.0
fsfe/reuse-tool pull request #774
Opened 2023-06-21 14:11 UTC by mxmehl

Explain the cause of some linting errors.

2023-06-21 14:15 UTC, carmenbianca requested changes
Another suggestion:

The bullet point '- More [files/file types] are recognised' is duplicated. Let's remove one of them :)

2023-06-21 14:15 UTC, carmenbianca commented on CHANGELOG.md
> +them have been requested by a lot of people. Probably most notably is the
notably → notable

2023-06-21 14:15 UTC, carmenbianca commented on CHANGELOG.md
> +copyright information. In the old version, of a file was described by more than
of → if

2023-06-21 14:15 UTC, carmenbianca commented on CHANGELOG.md
> +one source, the information has been merged. This often lead to unexpected
has been → would be

lead → led

2023-06-21 14:15 UTC, carmenbianca commented on CHANGELOG.md
> +transparent and understandable. Please take the time to fix the uncertainties in
this way to [...] → this way to strictly enforce a single source of truth for copyright and licensing information.

2023-06-21 14:19 UTC, mxmehl commented on CHANGELOG.md
> +them have been requested by a lot of people. Probably most notably is the
```suggestion
them have been requested by a lot of people. Probably most notable is the
```

2023-06-22 08:23 UTC, carmenbianca commented
Closing this in favour of #777

2023-06-22 08:23 UTC, closed without merging