feat: no strict dep5 parsing
fsfe/reuse-tool pull request #805
Opened 2023-07-19 19:21 UTC by nicorikken

Since version 0.1.47 of python-debian the dep5 parsing is strict. This is causing issues for certain users that have multiple Copyright statements in their Dep5 file. Disablng strictness removes the issue for those users.

Closes #803

2023-07-19 19:31 UTC, carmenbianca requested changes
This is missing a test. The test can be as simple as 'does not raise an error when trying to parse a (slightly? very?) incorrect DEP5 file'.

2023-07-20 06:31 UTC, nicorikken commented
This fails in its current state as multiple copyright fields are simply ignored.

2023-07-22 17:23 UTC, carmenbianca approved these changes
I've adjusted the tests a little. No functional changes; just refactored to no longer call to_dict_lint.

2023-07-23 09:39 UTC, carmenbianca commented
I am no longer certain if I want to merge this.

I took a look at python-debian 0.1.38 (the lowest compatible version according to pyproject.toml), and strict mode was _always_ enabled.

https://salsa.debian.org/python-debian-team/python-debian/-/blob/0.1.38/lib/debian/copyright.py#L130

I have to assume that python-debian recently included 'no duplicate fields' in their checks, which is fine, but simply disabling this now results in _other_ breakage.

Specifically, the following checks (in 0.1.38, but I'm going to assume that they exist after 0.1.38 also):

```python
                    _complain('Non-header paragraph has neither "Files" nor '
                              '"License" fields', strict)

[...]

            if 'Copyright' not in data:
                _complain('Files paragraph missing Copyright field', strict)
            if 'License' not in data:
                _complain('Files paragraph missing License field', strict)

            if not self.files:
                _complain('Files paragraph has empty Files field', strict)
```

I am fairly certain that we do need/want these checks.

2023-07-24 06:07 UTC, nicorikken commented
@carmenbianca Good catch, then merging #808 seems more appropriate.

2023-07-24 06:07 UTC, closed without merging