feat: lint output per line
fsfe/reuse-tool pull request #956
Opened 2024-04-10 18:35 UTC by nicorikken

Adds an '-line' or '-l' option to the 'lint' command. Prints a line for
each error, starting with the file to which the error belongs.

This output can be a starting point for some parsers, in particular ones
that implement something similar to Vim errorformat parsing.

Related to https://github.com/fsfe/reuse-tool/issues/925

Additional work needed:

- [ ] Needs tests
- [ ] Error messages might have to be improved
- [ ] Not all errors are found, as some issues aren't in the
  FileReports. This requires additional investigation.

Signed-off-by: Nico Rikken <nico@nicorikken.eu>

2024-04-20 06:55 UTC, nicorikken commented
Current version works based on ProjectReport to ensure also license errors are included. A structural improvement might be to create structural reports for license errors, even as FileReports.

2024-04-22 05:27 UTC, nicorikken commented
Two remaining suggestions for the future:

- Include source code line numbers of the finding. Requires keeping track of this information when detecting
- How best to deal with edge-case filenames that include colons and spaces?

Current output:

```
/tmp/pytest-of-nico/pytest-44/fake_repository14/invalid-license.py: bad license: invalid
LICENSES/invalid-license-text: bad license: invalid-license-text
LICENSES/Nokia-Qt-exception-1.1.txt: deprecated license
LICENSES/MIT: license without file extension
/tmp/pytest-of-nico/pytest-44/fake_repository14/invalid-license.py: missing license: invalid
LICENSES/MIT: unused license
LICENSES/Nokia-Qt-exception-1.1.txt: unused license
LICENSES/invalid-license-text: unused license
/tmp/pytest-of-nico/pytest-44/fake_repository14/restricted.py: read error
/tmp/pytest-of-nico/pytest-44/fake_repository14/file with spaces.py: without license
/tmp/pytest-of-nico/pytest-44/fake_repository14/file:with:colons.py: without license
/tmp/pytest-of-nico/pytest-44/fake_repository14/no-license.py: without license
/tmp/pytest-of-nico/pytest-44/fake_repository14/file with spaces.py: without copyright
/tmp/pytest-of-nico/pytest-44/fake_repository14/file:with:colons.py: without copyright
/tmp/pytest-of-nico/pytest-44/fake_repository14/invalid-license.py: without copyright
```

2024-04-22 06:03 UTC, nicorikken commented
I'm now trying to validate with the [errorformat library](https://github.com/reviewdog/errorformat): `errorformat "%f: %m"`
It seems it cannot succesfully parse the output of files with spaces and colons:
```
/tmp/pytest-of-nico/pytest-44/fake_repository14/invalid-license.py|| bad license invalid
LICENSES/invalid-license-text|| bad license: invalid-license-text
LICENSES/Nokia-Qt-exception-1.1.txt|| deprecated license
LICENSES/MIT|| license without file extension
/tmp/pytest-of-nico/pytest-44/fake_repository14/invalid-license.py|| missing license invalid
LICENSES/MIT|| unused license
LICENSES/Nokia-Qt-exception-1.1.txt|| unused license
LICENSES/invalid-license-text|| unused license
/tmp/pytest-of-nico/pytest-44/fake_repository14/restricted.py|| read error
|| /tmp/pytest-of-nico/pytest-44/fake_repository14/file with spaces.py: without license
/tmp/pytest-of-nico/pytest-44/fake_repository14/file:with:colons.py|| without license
/tmp/pytest-of-nico/pytest-44/fake_repository14/no-license.py|| without license
|| /tmp/pytest-of-nico/pytest-44/fake_repository14/file with spaces.py: without copyright
/tmp/pytest-of-nico/pytest-44/fake_repository14/file:with:colons.py|| without copyright
/tmp/pytest-of-nico/pytest-44/fake_repository14/invalid-license.py|| without copyright
```

So probably **filenames will have to be escaped.**

2024-04-22 19:04 UTC, nicorikken commented
I originally had a test with a filename with colons, but this was causing errors on Windows. I removed it.

2024-04-23 03:42 UTC, nicorikken commented
The issue of using files with spaces seems to be an issue with the `errorformat` library: https://github.com/reviewdog/errorformat/issues/97 I don't think reuse-tool needs to escape filename output as there is already a clear separator in this output.
This leaves the edge-case of filenames with colons, but this is also rare in a development environment that will have to cater to Windows which doesn't allow colons in filenames.

2024-04-27 09:05 UTC, carmenbianca requested changes
Thanks a lot for this feature @nicorikken ! Two very small nitpicks which I will patch up.

2024-04-27 09:05 UTC, carmenbianca commented on src/reuse/lint.py
> +                output.write(_(f"{file}: bad license {lic}\n"))
Here and elsewhere, `_(f"{value}")` does not correctly translate. The formatting happens before the translation step here, while it should happen after.

2024-04-27 10:02 UTC, carmenbianca commented
I also spent a while looking at escaping options. Thank you @nicorikken for your analysis. I think there are only two characters that really concern us here:

- Newlines in filenames (yes...)
- Colons in filenames

I gave it a spin with Pylint to see how other tools handle it. Here's the result:

```
$ pylint src/reuse
************* Module reuse.hello
world
src/reuse/hello
world.py:1:0: C0103: Module name "hello
world" doesn't conform to snake_case naming style (invalid-name)
************* Module reuse.hello:world
src/reuse/hello:world.py:1:0: C0103: Module name "hello:world" doesn't conform to snake_case naming style (invalid-name)
```

The answer is: don't.

I think we can be lazy about this and not bother.

2024-04-27 10:07 UTC, carmenbianca approved these changes

2024-05-28 12:40 UTC, merged